-- 快速注释
require 'small-plug.comment-nvim'
-- 自动括号
require 'small-plug.pears-config'
-- 光标移动
require 'small-plug.leap-and-flit'
-- 片段测试
require 'small-plug.sniprun-config'
-- 动画
require 'small-plug.cellular-automaton'
